// Shared Defines
#undef OBJECT_BASIC_VECTOR2D
#undef OBJECT_BASIC_VECTOR3D
// Allocator specific defines
#undef OBJECT_LOCAL_OVERRIDE_STATIC_ACCESS_VECTOR2D
#undef OBJECT_LOCAL_OVERRIDE_STATIC_ACCESS_VECTOR3D
#undef ALLOCATOR_GLOBAL_ACCESS 
#undef CONSTRUCTOR_PARAMETERS

#undef IBM_BURSTS_IMPLEMENTATION_DETAILS