// Shared Defines
#undef OBJECT_BASIC_VECTOR2D
#undef OBJECT_BASIC_VECTOR3D

// Allocator specific defines
#undef OBJECT_LOCAL_OVERRIDE_GLOBAL_ACCESS_VECTOR2D
#undef OBJECT_LOCAL_OVERRIDE_GLOBAL_ACCESS_VECTOR3D

#undef OBJECT_LOCAL_OVERRIDE_SINGLETON_ACCESS_VECTOR2D
#undef OBJECT_LOCAL_OVERRIDE_SINGLETON_ACCESS_VECTOR3D

#undef ALLOCATOR_TEMPLATE_GLOBAL_ACCESS					
#undef ALLOCATOR_SINGLETON_ACCESS
#undef ALLOCATOR_GLOBAL_ACCESS 

#undef CONSTRUCTOR_PARAMETERS

#undef IBM_BURSTS_IMPLEMENTATION_DETAILS